# Generated by Django 5.2.9 on 2025-12-24 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('view', 'Visualização')], max_length=20, verbose_name='Ação')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model')),
                ('object_id', models.CharField(max_length=255, verbose_name='ID do Objeto')),
                ('field_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campo')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor Antigo')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('is_personal_data', models.BooleanField(db_index=True, default=False, verbose_name='Dados Pessoais')),
                ('data_subject', models.CharField(blank=True, help_text='Email ou identificador do titular dos dados', max_length=255, null=True, verbose_name='Titular dos Dados')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='core_auditl_company_c91423_idx'), models.Index(fields=['company', 'is_personal_data', 'created_at'], name='core_auditl_company_e12307_idx'), models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['data_subject', 'created_at'], name='core_auditl_data_su_dc3dfc_idx')],
            },
        ),
    ]
