# Generated by Django 5.2.9 on 2025-12-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Opcional. 150 caracteres ou menos. Letras, dígitos e @/./+/-/_ apenas.', max_length=150, null=True, verbose_name='username'),
        ),
    ]
