# Generated by Django 5.2.9 on 2025-12-24 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocumentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Aceito em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to='accounts.company', verbose_name='Empresa')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='accounts.legaldocument', verbose_name='Documento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aceitação de Documento Legal',
                'verbose_name_plural': 'Aceitações de Documentos Legais',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'accepted_at'], name='accounts_le_user_id_4c687b_idx'), models.Index(fields=['company', 'accepted_at'], name='accounts_le_company_c6630a_idx'), models.Index(fields=['document', 'accepted_at'], name='accounts_le_documen_00071e_idx')],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
