# Generated by Django 5.2.9 on 2025-12-24 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_legaldocumentacceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para documentos globais do sistema (padrão).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='accounts.company', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['company', 'document_type', 'is_active'], name='accounts_le_company_87b1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['document_type', 'is_active'], name='accounts_le_documen_25a1f0_idx'),
        ),
    ]
