# Generated by Django 5.2.9 on 2025-12-24 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_legaldocument_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocumentacceptance',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa do usuário (pode ser None se usuário não tiver company ou documento for global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to='accounts.company', verbose_name='Empresa'),
        ),
    ]
