# Generated by Django 5.2.9 on 2025-12-24 02:56

from django.db import migrations, models


def remove_duplicate_documents(apps, schema_editor):
    """Remove documentos duplicados, mantendo apenas um por document_type/version."""
    LegalDocument = apps.get_model('accounts', 'LegalDocument')

    # Agrupar por document_type e version
    from collections import defaultdict
    groups = defaultdict(list)

    for doc in LegalDocument.objects.all():
        key = (doc.document_type, doc.version)
        groups[key].append(doc)

    # Para cada grupo, manter apenas o primeiro documento (preferir globais se houver)
    for (doc_type, version), docs in groups.items():
        if len(docs) <= 1:
            continue

        # Separar globais (company=None) e específicos
        global_docs = [d for d in docs if d.company_id is None]
        company_docs = [d for d in docs if d.company_id is not None]

        if global_docs:
            # Manter apenas o primeiro documento global
            keep = global_docs[0]
            # Deletar outros globais e todos os específicos de company
            to_delete = [d for d in docs if d.id != keep.id]
        else:
            # Se não há globais, manter o primeiro e deletar os outros
            keep = docs[0]
            to_delete = docs[1:]

        for doc in to_delete:
            doc.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_legaldocumentacceptance_company'),
    ]

    operations = [
        # Primeiro, remover duplicatas
        migrations.RunPython(remove_duplicate_documents, migrations.RunPython.noop),
        # Depois, remover índices e campo
        migrations.RemoveIndex(
            model_name='legaldocument',
            name='accounts_le_company_87b1cf_idx',
        ),
        migrations.AlterUniqueTogether(
            name='legaldocument',
            unique_together={('document_type', 'version')},
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='content',
            field=models.TextField(help_text='Template com variáveis [VARIAVEL] ou {{variavel}} que serão substituídas por valores do SaaS.', verbose_name='Conteúdo'),
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='company',
        ),
    ]
