# Generated by Django 5.2.9 on 2025-12-24 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_company_2d29e3_idx',
            old_name='leads_lead_company_f5f6b1_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_company_222d77_idx',
            old_name='leads_lead_company_663c7d_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='Empresa'),
        ),
    ]
