# Generated by Django 5.2.9 on 2025-12-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_leads_lead_company_f5f6b1_idx_leads_lead_company_2d29e3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
    ]
